### ISSUE TITLE
Properties e Atributos privados

### ISSUE THREAD

**Issue by Marlysson** [Lrcezimbra/pysympla#3]
Estava vendo esse trecho as duas linhas que se seguem:

https://github.com/Lrcezimbra/pysympla/blob/bf87dd62dd57a45b5fe00ffb9b7c16c82163a44c/pysympla/event.py#L6

https://github.com/Lrcezimbra/pysympla/blob/bf87dd62dd57a45b5fe00ffb9b7c16c82163a44c/pysympla/event.py#L7

Por que criar esses atributos com underscore e associar à properties?

Poderia funcionar somente as properties , elas funcionando como atributos da instância.

Em algum lugar esses atributos são definidos? Pois eles iniciam em 0 e é feito a verificação se eles estão "vazios" ou não.

**Comment by lucasrcezimbra** [comment]
A minha ideia ao implementar dessa forma foi _cachear_, encapsular os dados e deixa-los _lazy_, explico:

- encapsulamento: os atributos com underscore ficam "privados" e só são acessados pelo método property, não podendo ser setado um valor (não vi sentido em poder setar um valor em um propriedade que deve ser extraída do Sympla)
- _lazy_: os atributos só são setados durante a execução do método `@property`. Não é necessário percorrer a árvore HTML e extrair esses dados no construtor sendo que talvez o usuário não queira usa-los, então o `soup.find` só ocorre dentro da property, quando o usuário realmente quiser acessar os dados.
- _cache_: caso um atributo já tenha um valor, ele é retornado, se não ele é extraído do HTML do Sympla e fica salvo https://github.com/Lrcezimbra/pysympla/blob/bf87dd62dd57a45b5fe00ffb9b7c16c82163a44c/pysympla/event.py#L12-L15

Criando os atributos com underscore foi a melhor maneira que achei de implementar com essas características citadas. 

Caso não tenho entendido minha explicação ou tenha outra forma de implementar, fique a vontade para comentar.

**Comment by Marlysson** [comment]
Opa, belo design dessa parte.. analisei um pouco aqui e faz todo sentido.

Pensei no decorator @lru_cache com essa parte de cache que foi citada.. acredito que seria interessante..

Belo projeto.
